apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: 739275484452.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo:v2
          ports:
            - containerPort: 8080
