name: CI
run-name: Manual Run by @${{ github.actor }}

on:
    
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  fetch_code:
    name: "Fetch_Code"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
      - uses: actions/checkout@v7

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate repository
        run: |
          echo "Running CI validation"
          test -f README.md
          test -f version.txt

  version_display:
    name: "show_version"
    runs-on: ubuntu-latest
    steps:
      - name: Display version
        run: cat version.txt
