name: CI
run-name: Run by @${{ github.actor }}

on:
    
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main
env:
  APP_NAME: github-learning

jobs:
  Application_Name:
    name: "App Name"
    runs-on: ubuntu-latest
    steps:
      - name: Display application name
        run: echo "$APP_NAME"

  fetch-code:
    name: "Fetch-Code"
    runs-on: ubuntu-latest
    needs: Application_Name
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

  validate:
    name: "Repository-Validation"
    runs-on: ubuntu-latest
    needs: fetch-code
    steps:
      - name: Validate repository
        run: |
          echo "Running CI validation"
          test -f README.md
          test -f version.txt

  version_display:
    name: "show_version"
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Display version
        run: cat version.txt
